name: Build (Windows x64)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      PUBLISH_DIR: publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish CemuLauncher.slnx --configuration Release --runtime win-x64 --output ${{ env.PUBLISH_DIR }}

      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: CemuLauncher-x64
          path: ${{ env.PUBLISH_DIR }}/

      - name: Compile installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.8
        with:
          path: Installer/Installer.iss

      - name: Upload installer
        uses: actions/upload-artifact@v7
        with:
          name: CemuLauncher-x64-Installer
          path: Installer/Output/CemuLauncher-x64-Setup.exe
          archive: false
